
#ifndef NEW_NODE_PLACEMENT
#define NEW_NODE_PLACEMENT
#endif

#define mNode new NEW_NODE_PLACEMENT sNode
#define mPosNode new NEW_NODE_PLACEMENT sPosNode
#define mIdList new NEW_NODE_PLACEMENT sIdList
#define mName new NEW_NODE_PLACEMENT sName
#define mSimpleName new NEW_NODE_PLACEMENT sSimpleName
#define mOpSymbol new NEW_NODE_PLACEMENT sOpSymbol
#define mSelName new NEW_NODE_PLACEMENT sSelName
#define mIftsName new NEW_NODE_PLACEMENT sIftsName
#define mAttributeName new NEW_NODE_PLACEMENT sAttributeName
#define mSelNameList new NEW_NODE_PLACEMENT sSelNameList
#define mDeclaration new NEW_NODE_PLACEMENT sDeclaration
#define mAttributedDeclaration new NEW_NODE_PLACEMENT sAttributedDeclaration
#define mAttribute new NEW_NODE_PLACEMENT sAttribute
#define mAttributeValue new NEW_NODE_PLACEMENT sAttributeValue
#define mScope new NEW_NODE_PLACEMENT sScope
#define mTopScope new NEW_NODE_PLACEMENT sTopScope
#define mLibNameDecl new NEW_NODE_PLACEMENT sLibNameDecl
#define mIndirectDecl new NEW_NODE_PLACEMENT sIndirectDecl
#define mPackage new NEW_NODE_PLACEMENT sPackage
#define mStandardPackage new NEW_NODE_PLACEMENT sStandardPackage
#define mPackageBody new NEW_NODE_PLACEMENT sPackageBody
#define mType new NEW_NODE_PLACEMENT sType
#define mConstraint new NEW_NODE_PLACEMENT sConstraint
#define mRange new NEW_NODE_PLACEMENT sRange
#define mExplicitRange new NEW_NODE_PLACEMENT sExplicitRange
#define mArrayRange new NEW_NODE_PLACEMENT sArrayRange
#define mArrayAttr_RANGE new NEW_NODE_PLACEMENT sArrayAttr_RANGE
#define mArrayAttr_REVERSE_RANGE new NEW_NODE_PLACEMENT sArrayAttr_REVERSE_RANGE
#define mPreIndexConstraint new NEW_NODE_PLACEMENT sPreIndexConstraint
#define mPreIndexRangeConstraint new NEW_NODE_PLACEMENT sPreIndexRangeConstraint
#define mPreIndexSubtypeConstraint new NEW_NODE_PLACEMENT sPreIndexSubtypeConstraint
#define mIndexConstraint new NEW_NODE_PLACEMENT sIndexConstraint
#define mIncompleteType new NEW_NODE_PLACEMENT sIncompleteType
#define mSubType new NEW_NODE_PLACEMENT sSubType
#define mAccessType new NEW_NODE_PLACEMENT sAccessType
#define mScalarType new NEW_NODE_PLACEMENT sScalarType
#define mNumericType new NEW_NODE_PLACEMENT sNumericType
#define mIntegerType new NEW_NODE_PLACEMENT sIntegerType
#define mFloatingType new NEW_NODE_PLACEMENT sFloatingType
#define mUniversalInteger new NEW_NODE_PLACEMENT sUniversalInteger
#define mUniversalReal new NEW_NODE_PLACEMENT sUniversalReal
#define mPhysicalType new NEW_NODE_PLACEMENT sPhysicalType
#define mPhysicalUnit new NEW_NODE_PLACEMENT sPhysicalUnit
#define mEnumType new NEW_NODE_PLACEMENT sEnumType
#define mEnumLiteral new NEW_NODE_PLACEMENT sEnumLiteral
#define mCompositeType new NEW_NODE_PLACEMENT sCompositeType
#define mArrayType new NEW_NODE_PLACEMENT sArrayType
#define mIndexType new NEW_NODE_PLACEMENT sIndexType
#define mSubarrayType new NEW_NODE_PLACEMENT sSubarrayType
#define mRecordType new NEW_NODE_PLACEMENT sRecordType
#define mRecordElement new NEW_NODE_PLACEMENT sRecordElement
#define mFileType new NEW_NODE_PLACEMENT sFileType
#define mDummyType new NEW_NODE_PLACEMENT sDummyType
#define mObject new NEW_NODE_PLACEMENT sObject
#define mVariable new NEW_NODE_PLACEMENT sVariable
#define mConstant new NEW_NODE_PLACEMENT sConstant
#define mConstantBody new NEW_NODE_PLACEMENT sConstantBody
#define mSignal new NEW_NODE_PLACEMENT sSignal
#define mGuardSignal new NEW_NODE_PLACEMENT sGuardSignal
#define mAlias new NEW_NODE_PLACEMENT sAlias
#define mFile new NEW_NODE_PLACEMENT sFile
#define mSubprogram new NEW_NODE_PLACEMENT sSubprogram
#define mProcedure new NEW_NODE_PLACEMENT sProcedure
#define mFunction new NEW_NODE_PLACEMENT sFunction
#define mPredefOp new NEW_NODE_PLACEMENT sPredefOp
#define mInterface new NEW_NODE_PLACEMENT sInterface
#define mSubprogramBody new NEW_NODE_PLACEMENT sSubprogramBody
#define mExpr new NEW_NODE_PLACEMENT sExpr
#define mUnresolvedName new NEW_NODE_PLACEMENT sUnresolvedName
#define mFunctionCall new NEW_NODE_PLACEMENT sFunctionCall
#define mProcedureCall new NEW_NODE_PLACEMENT sProcedureCall
#define mAmbgCall new NEW_NODE_PLACEMENT sAmbgCall
#define mGenAssocElem new NEW_NODE_PLACEMENT sGenAssocElem
#define mNamedAssocElem new NEW_NODE_PLACEMENT sNamedAssocElem
#define mSubtypeAssocElem new NEW_NODE_PLACEMENT sSubtypeAssocElem
#define mRangeAssocElem new NEW_NODE_PLACEMENT sRangeAssocElem
#define mAssociation new NEW_NODE_PLACEMENT sAssociation
#define mTypeConversion new NEW_NODE_PLACEMENT sTypeConversion
#define mQualifiedExpr new NEW_NODE_PLACEMENT sQualifiedExpr
#define mNewExpr new NEW_NODE_PLACEMENT sNewExpr
#define mPrimaryExpr new NEW_NODE_PLACEMENT sPrimaryExpr
#define mOpenExpr new NEW_NODE_PLACEMENT sOpenExpr
#define mLiteralRef new NEW_NODE_PLACEMENT sLiteralRef
#define mAmbgArrayLitRef new NEW_NODE_PLACEMENT sAmbgArrayLitRef
#define mArrayLiteralRef new NEW_NODE_PLACEMENT sArrayLiteralRef
#define mPhysicalLiteralRef new NEW_NODE_PLACEMENT sPhysicalLiteralRef
#define mAmbgNullExpr new NEW_NODE_PLACEMENT sAmbgNullExpr
#define mNullExpr new NEW_NODE_PLACEMENT sNullExpr
#define mObjectRef new NEW_NODE_PLACEMENT sObjectRef
#define mSimpleObjectRef new NEW_NODE_PLACEMENT sSimpleObjectRef
#define mAccessObjectRef new NEW_NODE_PLACEMENT sAccessObjectRef
#define mRecordObjectRef new NEW_NODE_PLACEMENT sRecordObjectRef
#define mGenericArrayObjectRef new NEW_NODE_PLACEMENT sGenericArrayObjectRef
#define mArrayObjectRef new NEW_NODE_PLACEMENT sArrayObjectRef
#define mIndexValue new NEW_NODE_PLACEMENT sIndexValue
#define mSliceObjectRef new NEW_NODE_PLACEMENT sSliceObjectRef
#define mEnumLitRef new NEW_NODE_PLACEMENT sEnumLitRef
#define mAmbgEnumLitRef new NEW_NODE_PLACEMENT sAmbgEnumLitRef
#define mAttrSignalRef new NEW_NODE_PLACEMENT sAttrSignalRef
#define mAttr_DELAYED new NEW_NODE_PLACEMENT sAttr_DELAYED
#define mAttr_STABLE new NEW_NODE_PLACEMENT sAttr_STABLE
#define mAttr_QUIET new NEW_NODE_PLACEMENT sAttr_QUIET
#define mAttr_TRANSACTION new NEW_NODE_PLACEMENT sAttr_TRANSACTION
#define mAttrFunctionCall new NEW_NODE_PLACEMENT sAttrFunctionCall
#define mAttrSigFunc new NEW_NODE_PLACEMENT sAttrSigFunc
#define mAttr_EVENT new NEW_NODE_PLACEMENT sAttr_EVENT
#define mAttr_ACTIVE new NEW_NODE_PLACEMENT sAttr_ACTIVE
#define mAttr_LAST_EVENT new NEW_NODE_PLACEMENT sAttr_LAST_EVENT
#define mAttr_LAST_ACTIVE new NEW_NODE_PLACEMENT sAttr_LAST_ACTIVE
#define mAttr_LAST_VALUE new NEW_NODE_PLACEMENT sAttr_LAST_VALUE
#define mAttr_DRIVING new NEW_NODE_PLACEMENT sAttr_DRIVING
#define mAttr_DRIVING_VALUE new NEW_NODE_PLACEMENT sAttr_DRIVING_VALUE
#define mAttrTypeFunc new NEW_NODE_PLACEMENT sAttrTypeFunc
#define mAttr_LEFT new NEW_NODE_PLACEMENT sAttr_LEFT
#define mAttr_RIGHT new NEW_NODE_PLACEMENT sAttr_RIGHT
#define mAttr_LOW new NEW_NODE_PLACEMENT sAttr_LOW
#define mAttr_HIGH new NEW_NODE_PLACEMENT sAttr_HIGH
#define mAttr_ASCENDING new NEW_NODE_PLACEMENT sAttr_ASCENDING
#define mAttr_IMAGE new NEW_NODE_PLACEMENT sAttr_IMAGE
#define mAttr_VALUE new NEW_NODE_PLACEMENT sAttr_VALUE
#define mAttr_POS new NEW_NODE_PLACEMENT sAttr_POS
#define mAttr_VAL new NEW_NODE_PLACEMENT sAttr_VAL
#define mAttr_SUCC new NEW_NODE_PLACEMENT sAttr_SUCC
#define mAttr_PRED new NEW_NODE_PLACEMENT sAttr_PRED
#define mAttr_LEFTOF new NEW_NODE_PLACEMENT sAttr_LEFTOF
#define mAttr_RIGHTOF new NEW_NODE_PLACEMENT sAttr_RIGHTOF
#define mArrayAttr new NEW_NODE_PLACEMENT sArrayAttr
#define mArrayAttr_LEFT new NEW_NODE_PLACEMENT sArrayAttr_LEFT
#define mArrayAttr_RIGHT new NEW_NODE_PLACEMENT sArrayAttr_RIGHT
#define mArrayAttr_HIGH new NEW_NODE_PLACEMENT sArrayAttr_HIGH
#define mArrayAttr_LOW new NEW_NODE_PLACEMENT sArrayAttr_LOW
#define mArrayAttr_ASCENDING new NEW_NODE_PLACEMENT sArrayAttr_ASCENDING
#define mArrayAttr_LENGTH new NEW_NODE_PLACEMENT sArrayAttr_LENGTH
#define mAttributeSpec new NEW_NODE_PLACEMENT sAttributeSpec
#define mEntitySpec new NEW_NODE_PLACEMENT sEntitySpec
#define mEntityNameList new NEW_NODE_PLACEMENT sEntityNameList
#define mEntityNameList_Ids new NEW_NODE_PLACEMENT sEntityNameList_Ids
#define mEntityNameList_ALL new NEW_NODE_PLACEMENT sEntityNameList_ALL
#define mEntityNameList_OTHERS new NEW_NODE_PLACEMENT sEntityNameList_OTHERS
#define mAggregate new NEW_NODE_PLACEMENT sAggregate
#define mRecordAggregate new NEW_NODE_PLACEMENT sRecordAggregate
#define mRecAggrAssoc new NEW_NODE_PLACEMENT sRecAggrAssoc
#define mArrayAggregate new NEW_NODE_PLACEMENT sArrayAggregate
#define mArrAggrAssoc new NEW_NODE_PLACEMENT sArrAggrAssoc
#define mSingleArrAggrAssoc new NEW_NODE_PLACEMENT sSingleArrAggrAssoc
#define mRangeArrAggrAssoc new NEW_NODE_PLACEMENT sRangeArrAggrAssoc
#define mSliceArrAggrAssoc new NEW_NODE_PLACEMENT sSliceArrAggrAssoc
#define mOthersArrAggrAssoc new NEW_NODE_PLACEMENT sOthersArrAggrAssoc
#define mAmbgAggregate new NEW_NODE_PLACEMENT sAmbgAggregate
#define mArtificialAmbgAggregate new NEW_NODE_PLACEMENT sArtificialAmbgAggregate
#define mElemAssoc new NEW_NODE_PLACEMENT sElemAssoc
#define mChoice new NEW_NODE_PLACEMENT sChoice
#define mExprChoice new NEW_NODE_PLACEMENT sExprChoice
#define mRangeChoice new NEW_NODE_PLACEMENT sRangeChoice
#define mNamedChoice new NEW_NODE_PLACEMENT sNamedChoice
#define mOthersChoice new NEW_NODE_PLACEMENT sOthersChoice
#define mLabel new NEW_NODE_PLACEMENT sLabel
#define mStatement new NEW_NODE_PLACEMENT sStatement
#define mDummyStat new NEW_NODE_PLACEMENT sDummyStat
#define mReturnStat new NEW_NODE_PLACEMENT sReturnStat
#define mVarAssignment new NEW_NODE_PLACEMENT sVarAssignment
#define mIfStat new NEW_NODE_PLACEMENT sIfStat
#define mCaseStat new NEW_NODE_PLACEMENT sCaseStat
#define mCaseAlternative new NEW_NODE_PLACEMENT sCaseAlternative
#define mLoopStat new NEW_NODE_PLACEMENT sLoopStat
#define mLoopScope new NEW_NODE_PLACEMENT sLoopScope
#define mIterationScheme new NEW_NODE_PLACEMENT sIterationScheme
#define mWhileScheme new NEW_NODE_PLACEMENT sWhileScheme
#define mForScheme new NEW_NODE_PLACEMENT sForScheme
#define mPreForScheme new NEW_NODE_PLACEMENT sPreForScheme
#define mLoopControlStat new NEW_NODE_PLACEMENT sLoopControlStat
#define mNextStat new NEW_NODE_PLACEMENT sNextStat
#define mExitStat new NEW_NODE_PLACEMENT sExitStat
#define mNullStat new NEW_NODE_PLACEMENT sNullStat
#define mProcedureCallStat new NEW_NODE_PLACEMENT sProcedureCallStat
#define mWaitStat new NEW_NODE_PLACEMENT sWaitStat
#define mSignalList new NEW_NODE_PLACEMENT sSignalList
#define mWaveformElement new NEW_NODE_PLACEMENT sWaveformElement
#define mSignalAssignment new NEW_NODE_PLACEMENT sSignalAssignment
#define mAssertStat new NEW_NODE_PLACEMENT sAssertStat
#define mConcurrentStatement new NEW_NODE_PLACEMENT sConcurrentStatement
#define mProcess new NEW_NODE_PLACEMENT sProcess
#define mCondalWaveform new NEW_NODE_PLACEMENT sCondalWaveform
#define mCondalSignalAssign new NEW_NODE_PLACEMENT sCondalSignalAssign
#define mComponent new NEW_NODE_PLACEMENT sComponent
#define mBlock new NEW_NODE_PLACEMENT sBlock
#define mEntity new NEW_NODE_PLACEMENT sEntity
#define mArchitecture new NEW_NODE_PLACEMENT sArchitecture
#define mBlockStat new NEW_NODE_PLACEMENT sBlockStat
#define mComponentInst new NEW_NODE_PLACEMENT sComponentInst
#define mConfigSpec new NEW_NODE_PLACEMENT sConfigSpec
#define mComponentSpec new NEW_NODE_PLACEMENT sComponentSpec
#define mInstList new NEW_NODE_PLACEMENT sInstList
#define mInstList_Ids new NEW_NODE_PLACEMENT sInstList_Ids
#define mInstList_ALL new NEW_NODE_PLACEMENT sInstList_ALL
#define mInstList_OTHERS new NEW_NODE_PLACEMENT sInstList_OTHERS
#define mBindingIndic new NEW_NODE_PLACEMENT sBindingIndic
#define mIncrementalBindingIndic new NEW_NODE_PLACEMENT sIncrementalBindingIndic
#define mConfiguration new NEW_NODE_PLACEMENT sConfiguration
#define mBaseConfig new NEW_NODE_PLACEMENT sBaseConfig
#define mBlockConfig new NEW_NODE_PLACEMENT sBlockConfig
#define mCompConfig new NEW_NODE_PLACEMENT sCompConfig
#define mCompInstList new NEW_NODE_PLACEMENT sCompInstList
#define mDummy new NEW_NODE_PLACEMENT sDummy
#define mAssociationList new NEW_NODE_PLACEMENT sAssociationList
